version: '3'
services:
  site:
    command: jekyll serve --watch --incremental
    image: jekyll/jekyll:4.0.0
    hostname: jekyll
    container_name: jekyll
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
